[package]
name = "rpx"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "rpx"
path = "src/main.rs"

[dependencies]
sdk-package = { path = "../sdk-package" }
serde_json = { workspace = true }
anyhow = { workspace = true }
zip = { version = "2", default-features = false, features = ["deflate"] }
