[package]
name = "core-lib"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "core_lib"
path = "src/lib.rs"

[dependencies]
config = { path = "../config" }
supervisor = { path = "../supervisor" }
security = { path = "../security" }
vault-process = { path = "../../../vault-process" }
tracing = { workspace = true }
tokio = { workspace = true }
