[package]
name = "vault-process"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vault = { path = "../vault" }
error-client = { path = "../error-client" }
atomic-io = { path = "../atomic-io" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
hex = "0.4"
