//! Versioned binary event packets and compile-time CTI log dictionaries.
//!
//! Guests/CC emit only compact numeric packets on the hot path. Human strings
//! live in the immutable dictionary and are rendered only by diagnostics/CLI
//! consumers. The packet deliberately carries no raw pointers or source text.

use std::collections::BTreeSet;
use std::fmt;

use crate::{CtiEventClass, CtiLogLevel, CTI_LOG_ABI_VERSION};

pub const TASK_EVENT_PACKET_BYTES: usize = 40;
pub const TASK_EVENT_MAX_DICTIONARY_ENTRIES: usize = u16::MAX as usize;
pub const TASK_EVENT_MAX_TEMPLATE_BYTES: usize = 1024;
pub const TASK_EVENT_MAX_SYMBOL_BYTES: usize = 512;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TaskEvent {
    pub timestamp_delta_ns: u64,
    pub execution_id: u64,
    pub event_id: u16,
    pub oid: u16,
    /// Zero means the event has no source site. Non-zero values resolve through
    /// the CTI ERROR_SITES/SOURCE_MAP metadata generated by RELC.
    pub site_id: u32,
    pub arg0: u64,
    pub arg1: u64,
}

impl TaskEvent {
    pub fn encode(self) -> [u8; TASK_EVENT_PACKET_BYTES] {
        let mut out = [0u8; TASK_EVENT_PACKET_BYTES];
        out[0..8].copy_from_slice(&self.timestamp_delta_ns.to_be_bytes());
        out[8..16].copy_from_slice(&self.execution_id.to_be_bytes());
        out[16..18].copy_from_slice(&self.event_id.to_be_bytes());
        out[18..20].copy_from_slice(&self.oid.to_be_bytes());
        out[20..24].copy_from_slice(&self.site_id.to_be_bytes());
        out[24..32].copy_from_slice(&self.arg0.to_be_bytes());
        out[32..40].copy_from_slice(&self.arg1.to_be_bytes());
        out
    }

    pub fn decode(bytes: [u8; TASK_EVENT_PACKET_BYTES]) -> Self {
        Self {
            timestamp_delta_ns: u64::from_be_bytes(bytes[0..8].try_into().expect("fixed slice")),
            execution_id: u64::from_be_bytes(bytes[8..16].try_into().expect("fixed slice")),
            event_id: u16::from_be_bytes(bytes[16..18].try_into().expect("fixed slice")),
            oid: u16::from_be_bytes(bytes[18..20].try_into().expect("fixed slice")),
            site_id: u32::from_be_bytes(bytes[20..24].try_into().expect("fixed slice")),
            arg0: u64::from_be_bytes(bytes[24..32].try_into().expect("fixed slice")),
            arg1: u64::from_be_bytes(bytes[32..40].try_into().expect("fixed slice")),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TaskEventDescriptor {
    pub event_id: u16,
    pub class: CtiEventClass,
    /// Minimum runtime logging mode that emits this event.
    pub level: CtiLogLevel,
    /// Compile-time symbol/operation identity. This is never used for dispatch.
    pub symbol: String,
    /// Human rendering template. Supported replacements are `{symbol}`, `{oid}`,
    /// `{site}`, `{arg0}`, and `{arg1}`.
    pub template: String,
}

impl TaskEventDescriptor {
    fn validate(&self) -> Result<(), TaskEventError> {
        if self.event_id == 0 {
            return Err(TaskEventError::InvalidDictionary(
                "event ID 0 is reserved for 'no event'".into(),
            ));
        }
        if self.symbol.is_empty()
            || self.symbol.len() > TASK_EVENT_MAX_SYMBOL_BYTES
            || self.symbol.chars().any(char::is_control)
        {
            return Err(TaskEventError::InvalidDictionary(format!(
                "event {} has invalid symbol metadata",
                self.event_id
            )));
        }
        if self.template.is_empty()
            || self.template.len() > TASK_EVENT_MAX_TEMPLATE_BYTES
            || self
                .template
                .chars()
                .any(|ch| ch.is_control() && ch != '\n' && ch != '\t')
        {
            return Err(TaskEventError::InvalidDictionary(format!(
                "event {} has invalid rendering template",
                self.event_id
            )));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TaskEventDictionary {
    pub abi_version: u16,
    entries: Vec<TaskEventDescriptor>,
}

impl TaskEventDictionary {
    pub fn new(mut entries: Vec<TaskEventDescriptor>) -> Result<Self, TaskEventError> {
        if entries.len() > TASK_EVENT_MAX_DICTIONARY_ENTRIES {
            return Err(TaskEventError::InvalidDictionary(format!(
                "event dictionary contains {} entries; maximum is {}",
                entries.len(),
                TASK_EVENT_MAX_DICTIONARY_ENTRIES
            )));
        }
        entries.sort_by_key(|entry| entry.event_id);
        let mut seen = BTreeSet::new();
        for entry in &entries {
            entry.validate()?;
            if !seen.insert(entry.event_id) {
                return Err(TaskEventError::InvalidDictionary(format!(
                    "duplicate event ID {}",
                    entry.event_id
                )));
            }
        }
        Ok(Self {
            abi_version: CTI_LOG_ABI_VERSION,
            entries,
        })
    }

    pub fn entries(&self) -> &[TaskEventDescriptor] {
        &self.entries
    }

    pub fn descriptor(&self, event_id: u16) -> Option<&TaskEventDescriptor> {
        self.entries
            .binary_search_by_key(&event_id, |entry| entry.event_id)
            .ok()
            .map(|index| &self.entries[index])
    }

    pub fn should_emit(&self, mode: CtiLogLevel, event_id: u16) -> bool {
        if mode == CtiLogLevel::Off {
            return false;
        }
        self.descriptor(event_id)
            .is_some_and(|descriptor| (descriptor.level as u8) <= (mode as u8))
    }

    /// Human rendering is intentionally outside the hot binary event path.
    pub fn render(&self, event: &TaskEvent) -> Result<String, TaskEventError> {
        let descriptor = self
            .descriptor(event.event_id)
            .ok_or(TaskEventError::UnknownEventId(event.event_id))?;
        let rendered = descriptor
            .template
            .replace("{symbol}", &descriptor.symbol)
            .replace("{oid}", &event.oid.to_string())
            .replace("{site}", &event.site_id.to_string())
            .replace("{arg0}", &event.arg0.to_string())
            .replace("{arg1}", &event.arg1.to_string());
        Ok(rendered)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskEventError {
    InvalidDictionary(String),
    UnknownEventId(u16),
}

impl fmt::Display for TaskEventError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidDictionary(message) => {
                write!(formatter, "invalid CTI log event dictionary: {message}")
            }
            Self::UnknownEventId(event_id) => {
                write!(formatter, "unknown CTI log event ID {event_id}")
            }
        }
    }
}

impl std::error::Error for TaskEventError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn event_packet_is_fixed_width_and_round_trips() {
        let event = TaskEvent {
            timestamp_delta_ns: 123,
            execution_id: 44,
            event_id: 7,
            oid: 31_844,
            site_id: 28,
            arg0: 9,
            arg1: 10,
        };
        let encoded = event.encode();
        assert_eq!(encoded.len(), TASK_EVENT_PACKET_BYTES);
        assert_eq!(TaskEvent::decode(encoded), event);
    }

    #[test]
    fn dictionary_filters_without_rendering_strings() {
        let dictionary = TaskEventDictionary::new(vec![
            TaskEventDescriptor {
                event_id: 2,
                class: CtiEventClass::Function,
                level: CtiLogLevel::Trace,
                symbol: "verifyPassword".into(),
                template: "FNCT : executed {symbol}".into(),
            },
            TaskEventDescriptor {
                event_id: 1,
                class: CtiEventClass::Error,
                level: CtiLogLevel::Error,
                symbol: "verifyPassword".into(),
                template: "ER : {symbol} failed at site {site}".into(),
            },
        ])
        .unwrap();

        assert!(dictionary.should_emit(CtiLogLevel::Error, 1));
        assert!(!dictionary.should_emit(CtiLogLevel::Error, 2));
        assert!(dictionary.should_emit(CtiLogLevel::Trace, 2));
        assert!(!dictionary.should_emit(CtiLogLevel::Off, 1));
    }

    #[test]
    fn renderer_resolves_dictionary_metadata_only_on_demand() {
        let dictionary = TaskEventDictionary::new(vec![TaskEventDescriptor {
            event_id: 9,
            class: CtiEventClass::Error,
            level: CtiLogLevel::Error,
            symbol: "verifyPassword".into(),
            template: "ER : Function {symbol} failed [oid={oid}] site={site}".into(),
        }])
        .unwrap();
        let event = TaskEvent {
            timestamp_delta_ns: 0,
            execution_id: 1,
            event_id: 9,
            oid: 31_848,
            site_id: 28,
            arg0: 0,
            arg1: 0,
        };
        assert_eq!(
            dictionary.render(&event).unwrap(),
            "ER : Function verifyPassword failed [oid=31848] site=28"
        );
    }

    #[test]
    fn duplicate_or_zero_event_ids_fail_closed() {
        let zero = TaskEventDictionary::new(vec![TaskEventDescriptor {
            event_id: 0,
            class: CtiEventClass::Task,
            level: CtiLogLevel::Task,
            symbol: "task".into(),
            template: "TASK : {symbol}".into(),
        }]);
        assert!(zero.is_err());

        let duplicate = TaskEventDictionary::new(vec![
            TaskEventDescriptor {
                event_id: 1,
                class: CtiEventClass::Task,
                level: CtiLogLevel::Task,
                symbol: "a".into(),
                template: "TASK : {symbol}".into(),
            },
            TaskEventDescriptor {
                event_id: 1,
                class: CtiEventClass::Task,
                level: CtiLogLevel::Task,
                symbol: "b".into(),
                template: "TASK : {symbol}".into(),
            },
        ]);
        assert!(duplicate.is_err());
    }
}
